### ISSUE TITLE
test pretrained model

### ISSUE THREAD

**Issue by Ricelll** [BeierZhu/Sturcture-Coherency-Face-Alignment#1]
Could u tell me it is the ResNet34 pretrained model in Google Drive?
i run the code, it occured to that "missing keys from checkpoint"
`....[WARNING]2021-06-24 18:55:16,953-misc.py#60:missing keys from checkpoint: module.backbone.layer4.2.bn1.BN.weight
[WARNING]2021-06-24 18:55:16,953-misc.py#60:missing keys from checkpoint: [module.backbone.layer2.0.bn2.BN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.1.bn2.IN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.bn2.BN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.0.downsample.1.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.bn2.BN.running_mean
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.2.bn2.BN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.0.bn2.IN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.4.bn2.BN.num_batches_tracked
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer1.0.bn1.IN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer1.2.bn2.BN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer1.1.bn1.IN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.3.bn1.BN.running_var
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.1.bn1.BN.running_mean
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.0.bn2.BN.running_mean
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.2.bn1.BN.running_var
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.3.bn2.BN.num_batches_tracked
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.bn1.BN.num_batches_tracked
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer1.2.bn2.BN.running_mean
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer1.0.bn1.BN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.3.bn1.IN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.3.bn1.IN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer3.2.bn1.IN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer2.0.bn2.IN.bias
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.0.bn1.IN.weight
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.bn1.BN.running_var
[WARNING]2021-06-24 18:55:16,954-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.bn1.IN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.4.bn1.BN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.2.bn1.BN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer2.3.bn2.BN.weight
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer1.2.bn1.IN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.0.downsample.0.weight
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.4.bn1.IN.weight
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer2.3.bn1.BN.running_var
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.5.bn2.BN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer2.2.bn2.IN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer1.0.bn2.BN.weight
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer4.1.conv2.conv.weight
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer1.2.bn1.BN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer2.1.bn1.BN.bias
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer3.1.bn2.BN.running_var
[WARNING]2021-06-24 18:55:16,955-misc.py#60:missing keys from checkpoint: module.backbone.layer1.1.bn1.BN.bias
`](url)

**Comment by BeierZhu** [comment]
The pretrained model in the ''main'' branch uses HRNet backbone. 
The config example in ''master'' branch uses ResNet34, and we didn't provide the pretrained model.

**Comment by Ricelll** [comment]
> The pretrained model in the ''main'' branch uses HRNet backbone.
> The config example in ''master'' branch uses ResNet34, and we didn't provide the pretrained model.
Thanks!!!

**Comment by Ricelll** [comment]
Thanks!!

**Comment by BeierZhu** [comment]
I just uploaded a ResNet34 model, which yields 4.55 NME (ION) on WFLW.   Here is download link [ResNet34](https://drive.google.com/file/d/1C4jNp1Hb8Aq0zh7wfUIimhb3P7-ezknT/view?usp=sharing)
