### ISSUE TITLE
training data preprocessing

### ISSUE THREAD

**Issue by kmlee3535** [BeierZhu/Sturcture-Coherency-Face-Alignment#4]
Hi! thanks for sharing your work. Your paper helped a lot with understanding the alignment task
But I have question with pre-processing data 
face images in the given train set was all straightly aligned and it seems like this wasn't in PFLD setseperation code.
How can I calculate the angle for rotating the face straightly and what is the padding ratio of the image? 
Can you share the code for this?

**Comment by BeierZhu** [comment]
HI, the standard algorithm to align face is Procrustes analysis. But I tried a simpler method (1) calculate the mean x and y coordinate of each landmark (2) for each image, calculate the Similarity Transformation Matrix that map the coordinates to the mean pose.

Sorry the code was written like 3 years ago, I cannot find it anymore.

**Comment by BeierZhu** [comment]
BTW, the code for Procrustes analysis is similar to the class **GuidedAffine** in my [align_transforms.py](https://github.com/BeierZhu/Sturcture-Coherency-Face-Alignment/blob/master/datasets/align_transforms.py).

**Comment by kmlee3535** [comment]
Thanks!!
